$_L(["java.io.FilterOutputStream"],"java.io.BufferedOutputStream",["java.io.IOException","java.lang.ArrayIndexOutOfBoundsException","$.IllegalArgumentException","$.NullPointerException"],function(){
c$=$_C(function(){
this.buf=null;
this.count=0;
$_Z(this,arguments);
},java.io,"BufferedOutputStream",java.io.FilterOutputStream);
$_K(c$,
function(out){
this.construct(out,8192);
},"java.io.OutputStream");
$_K(c$,
function(out,size){
$_R(this,java.io.BufferedOutputStream,[out]);
if(size<=0){
throw new IllegalArgumentException("size<=0");
}this.buf=$_A(size,0);
},"java.io.OutputStream,~N");
$_V(c$,"flush",
function(){
this.checkNotClosed();
this.flushInternal();
this.out.flush();
});
$_M(c$,"checkNotClosed",
($fz=function(){
if(this.buf==null){
throw new java.io.IOException("BufferedOutputStream is closed");
}},$fz.isPrivate=true,$fz));
$_M(c$,"write",
function(buffer,offset,length){
this.checkNotClosed();
if(buffer==null){
throw new NullPointerException("buffer==null");
}var internalBuffer=this.buf;
if(length>=internalBuffer.length){
this.flushInternal();
this.out.write(buffer,offset,length);
return;
}if(offset<0||offset>buffer.length-length){
throw new ArrayIndexOutOfBoundsException("Offset out of bounds:"+offset);
}if(length<0){
throw new ArrayIndexOutOfBoundsException("Length out of bounds:"+length);
}if(length>=(internalBuffer.length-this.count)){
this.flushInternal();
}System.arraycopy(buffer,offset,internalBuffer,this.count,length);
this.count+=length;
},"~A,~N,~N");
$_M(c$,"close",
function(){
if(this.buf==null){
return;
}try{
$_U(this,java.io.BufferedOutputStream,"close",[]);
}finally{
this.buf=null;
}
});
$_M(c$,"write",
function(oneByte){
this.checkNotClosed();
if(this.count==this.buf.length){
this.out.write(this.buf,0,this.count);
this.count=0;
}this.buf[this.count++]=oneByte;
},"~N");
$_M(c$,"flushInternal",
($fz=function(){
if(this.count>0){
this.out.write(this.buf,0,this.count);
this.count=0;
}},$fz.isPrivate=true,$fz));
});
