$_L(["java.util.Date"],"$wt.widgets.DesktopItem",null,function(){
c$=$_C(function(){
this.display=null;
this.handle=null;
this.isAutoHide=true;
this.lastUpdated=0;
this.isJustUpdated=false;
this.mouseAlreadyMoved=false;
this.layerZIndex=-1;
this.leaving=null;
this.leavingTimeoutHandle=0;
$_Z(this,arguments);
},$wt.widgets,"DesktopItem");
$_Y(c$,function(){
this.lastUpdated=new java.util.Date().getTime();
});
$_M(c$,"updateLastModified",
function(){
this.lastUpdated=new java.util.Date().getTime();
this.mouseAlreadyMoved=false;
if(this.isAutoHide){
if(this.leavingTimeoutHandle!=0){
w$.clearTimeout(this.leavingTimeoutHandle);
this.leavingTimeoutHandle=0;
}if(this.leaving==null){
this.leaving=$_Q((function(i$,v$){
if(!$_D("org.eclipse.swt.widgets.DesktopItem$1")){
$_H();
c$=$_W($wt.widgets,"DesktopItem$1",null,Runnable);
$_V(c$,"run",
function(){
if(!this.b$["$wt.widgets.DesktopItem"].mouseAlreadyMoved){
this.b$["$wt.widgets.DesktopItem"].handleLeaving();
}this.b$["$wt.widgets.DesktopItem"].leavingTimeoutHandle=0;
});
c$=$_P();
}
return $_N($wt.widgets.DesktopItem$1,i$,v$);
})(this,null));
}this.leavingTimeoutHandle=w$.setTimeout(this.leaving,2000);
}});
});
